### ISSUE TITLE
Not working with TypeScript

### ISSUE THREAD

**Issue by pjotrsavitski** [niftylettuce/url-regex-safe#14]
Would it be possible to make this package TypeScript friendly? This seems to be one thing that url-regex module had.

**Comment by niftylettuce** [comment]
I think you could add this to DefinitelyTyped stuff?  I don't use TS

**Comment by pjotrsavitski** [comment]
I did give it a go and it installed, then I found out that the fix in only applicable to the Node.js environment, which is not my case. My usage is within the browser with controlled data set, which makes this issue less severe.

**Comment by pjotrsavitski** [comment]
I've added a pull request with instructions for TypeScript usage. It would still be better to include the necessary files into the repository itself. I suppose that two .ts files from [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/url-regex-safe) would do the trick and allow installing just one package.
