### ISSUE TITLE
trailingPeriod setting not honored on subdomains

### ISSUE THREAD

**Issue by roger-obando** [niftylettuce/url-regex-safe#17]
Currently if I try to run urlRegexSafe on a string like 'http://www.google.com.' it will return 'http://www.google.com' as the first match but if I were to run it on 'http://www.google.com/subdir.' it will return 'http://www.google.com/subdir.' (trailing period included).  Is this the intended functionality?  How can I go about ensuring that trailing periods will always be ignored?

**Comment by weckbach** [comment]
+1

**Comment by niftylettuce** [comment]
PR welcome!

**Comment by birtles** [comment]
I worked around this by adapting the path part from:

`(?:[/?#][^\s")']*)?`

to:

`(?:[/?#][^\s")']*[^\s")'.?!])?`

which is probably not quite right but seemed to cover all the cases I threw at it

**Comment by titanism** [comment]
Can you submit a PR and maybe a test? @birtles would love to get this in

**Comment by birtles** [comment]
> Can you submit a PR and maybe a test? @birtles would love to get this in

Sure, I've submitted #29 for this.

**Comment by titanism** [comment]
v4.0.0 released with this, thank you @birtles 

release notes @ https://github.com/spamscanner/url-regex-safe/releases/tag/v4.0.0

*note: this version now requires node v14+*

**Comment by birtles** [comment]
Thank you! 🙏
