### ISSUE TITLE
re2 breaks builds

### ISSUE THREAD

**Issue by vicary** [niftylettuce/url-regex-safe#18]
This originates from https://github.com/uhop/node-re2/issues/92, affecting builds via webpack and esbuild, browser or TypeScript for servers all alike.

# Option 1

Change `re2` into a peer dependency, such that users can choose to install `re2` or not, depending on their situation. 

# Option 2

If the existence of `url-regex-safe` over `url-regex` means `re2` must be kept in `dependencies`, at least change the actual code to allow fallback to plain `RegExp`, so webpack/esbuild users can mark `re2` as *external* in build time until the issue above is fixed.

**Comment by niftylettuce** [comment]
v2.1.0 released which resolves this issue, thanks to @vicary for the PR

https://github.com/niftylettuce/url-regex-safe/releases/tag/v2.1.0

**Comment by niftylettuce** [comment]
See v3.0.0 https://github.com/spamscanner/url-regex-safe/releases/tag/v3.0.0
