### ISSUE TITLE
browser friendly

### ISSUE THREAD

**Issue by Kikobeats** [niftylettuce/url-regex-safe#2]
Hello,

I'm opening this issue because, although I adopted `url-regex-safe` instead of `url-regex`, recently discovered `url-regex-safe` depends on `re2` and it isn't a suitable browser dependency:

https://github.com/uhop/node-re2/issues/77#issuecomment-672936497

There is a proposition to make `re2` browser friendly

https://github.com/uhop/node-re2/issues/18

but until that happens, this is making me not possible to adopt `url-regex-safe`

not sure if you have an opinion about that, just I wanted to warn you 🙂

**Comment by Kikobeats** [comment]
Hum I think you're right and actually, the error I'm experimenting with is the environment where the code is running can't compile re2 properly


<img width="865" alt="Screen Shot 2020-10-14 at 00 43 32" src="https://user-images.githubusercontent.com/2096101/95923683-53702700-0db6-11eb-8053-696f037a6312.png">

<img width="1020" alt="Screen Shot 2020-10-14 at 00 42 55" src="https://user-images.githubusercontent.com/2096101/95923678-4fdca000-0db6-11eb-8198-fa28359483c1.png">

which is also a pain, any idea what's happening?

**Comment by niftylettuce** [comment]
If you can share a reproducible repo I could try to find time to look at this, guessing its a bundler issue or yarn/npm.   What version of Node are you on?

**Comment by Kikobeats** [comment]
reproducible example: https://runkit.com/kikobeats/5f85c1f39b9a71001a1025c7

**Comment by IsraelOrtuno** [comment]
Same here, I can't use in a simple Vue app 
```
Cannot find module './build/Release/re2' from 're2.js'
```

**Comment by phiberber** [comment]
Is it possible to be related with re2 install script not being called?

`install-from-cache --artifact build/Release/re2.node --host-var RE2_DOWNLOAD_MIRROR || npm run rebuild`.

Maybe url-regex-safe can't find the re2 module because the .node file wasn't installed yet. 

`const RE2 = require('./build/Release/re2');`

The solution may be to use lazy import with re2 or url-regex-safe.
