### ISSUE TITLE
Matches email addresses (within a larger string) with default options

### ISSUE THREAD

**Issue by surlyhacker** [niftylettuce/url-regex-safe#5]
If you take this string: "Please send an email to test@test.com, providing ONLY your first name", this module will return "test.com" as a match.

Is this intended behavior and I am just misunderstanding how it's supposed to work?

I see that the "auth" option (if set to true) may result in undesired matches to email addresses, but it defaults to false.
~~I don't see a test case in the tests for this scenario.~~ (see comment below)  

What's interesting is that you commented on this exact problem in a [relevant url-regex issue](https://github.com/kevva/url-regex/issues/51#issuecomment-674365606):

> We're using this library to pull urls out of a user input string. We're currently running into a problem where it returns email addresses.
> 
> ```
> 'This is an email@email.com'.match(urlRegex({ exact: false, strict: false }));
> // returns ['email@email.com']
> ```
> 
> I think it should return no matches in this case.

...

> This issue is fixed in my maintained and modern version of this package at https://github.com/niftylettuce/url-regex-safe. You should be able to switch from `url-regex` to `url-regex-safe` now. See the updated list of options as I added some new ones, and changed a few defaults to more sensible ones (since not everyone is parsing Markdown for instance).

Here are the relevant options that might impact this test, although they are all just their default values so wouldn't need to be explicitly set in a test:
exact: false
strict: false
auth: false

**Comment by surlyhacker** [comment]
Actually there is a test similar to this that seems counterintuitive given my limited understanding of the interplay between the options and the aforementioned comment on that issue with url-regex:
```
test('parses similar to Gmail by default', (t) => {
  t.deepEqual(
    "foo@bar.com [foo]@bar.com foo bar @foob.com 'text@example.com, some text'".match(
      urlRegex()
    ),
    ['bar.com', 'bar.com', 'foob.com', 'example.com']
  );
});
```
Is that test case supposed to be finding:
1) URLs with an [Authority component](https://tools.ietf.org/html/rfc3986#section-3.2.1) (hereafter referred to as "Authority URLs") that are missing a scheme and have no password? (e.g. normally http://foo@bar.com)
or
2) Email address URLs that are missing a scheme? (e.g. normally mailto:foo@bar.com)

I would suggest more detailed documentation to help eliminate ambiguity if this is in fact not a bug.  Although if it is not a bug, that brings up the question of whether this module can currently be configured to behave as desired in this issue report, or if that would be an enhancement.  Personally I see the value in use cases that separate email address from other types of URLs, and would want an option to explicitly include/exclude them.  

Moreover (and perhaps most importantly), in a string like "Please use this Authority URL with username: user@foo.com to access the site", I personally would not even consider that to be a valid Authority URL in any context whatsoever.  A string with that syntax is an email address.  In the modern world in the limited scenarios where Authority URLs are still used, they should always be be prefixed with a scheme and if they are not, they should not be considered Authority URLs regardless of what the spec (RFCs) say (in a context where email addresses may be present).

**Comment by niftylettuce** [comment]
I think you're looking for `email-regex-safe` instead.  Check out https://spamscanner.net and its source/tests for more insight into how I workaround parsing things out.

**Comment by niftylettuce** [comment]
You could use `email-regex-safe` to parse out the emails so it only parses out URL's.
