### ISSUE TITLE
closing bracket on wikipedia links is ignored

### ISSUE THREAD

**Issue by baiti** [niftylettuce/url-regex-safe#8]
If the text contains a link like this: "https://de.wikipedia.org/wiki/Grafenau_(W%C3%BCrttemberg)", the generated link looks like:
```
<a href="https://de.wikipedia.org/wiki/Grafenau_(W%C3%BCrttemberg">
```
The closing bracket at the end is not part of the link

**Comment by baiti** [comment]
I just noticed if I set `{parens: true}` the closing bracket gets parsed correctly. Is this the intended purpose of this flag? If yes, pls close the issue as "works as designed".

**Comment by niftylettuce** [comment]
Correct
